version: 2

groups:
  reviewers:
    required: 2
    teams:
      - seek-asia-style-guide-contributors
    # Enable github reviews when integration is sufficient:
    # https://github.com/pullapprove/support/issues/98#issuecomment-256447253
    # github_reviews:
    #   enabled: true
    approve_by_comment:
      enabled: false
