version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build-deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - status-check
      - run: git config --global user.name "Circle-CI";
      - run: git config --global user.email "srp-dev@seekasia.com";
      - run: npm run build-gh-pages  
      - run: npm run deploy-gh-pages  
workflows:
  version: 2
  status-check:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  deploy-ghpages:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master
